apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: red-team-app
  namespace: argocd
  finalizers:
  # The default behaviour is foreground cascading deletion
  - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: red-team-project

  # Source of the application manifests
  source:
    directory:
      recurse: true
    path: manifests/red-team
    repoURL: https://github.com/mmoreiradj/cluster-panic-gitops.git
    targetRevision: HEAD

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: app-namespace

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PrunePropagationPolicy=background
    #- CreateNamespace=true
    # managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
    #   labels:
    #     pod-security.kubernetes.io/enforce: restricted

    # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
    # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
    # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
    # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 3