apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: llm-on-call-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: lLLM On Call

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/mmoreiradj/llm-on-call.git'
  # Only permit applications to deploy to the 'guestbook' namespace or any namespace starting with 'guestbook-' in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: llm-on-call
    server: https://kubernetes.default.svc
    name: in-cluster
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles: []