image:
  repository: microservices-names-service
  tag: latest

podLabels: 
  app.kubernetes.io/name: names-service 

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
