image:
  repository: microservices-verbes-service
  tag: latest

podLabels: 
  app.kubernetes.io/name: verbs-service
  
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
