apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: "https://github.com/mmoreiradj/llm-on-call"
  branch: feat/fleet
  paths:
  - kubernetes/charts/gateway
  - kubernetes/charts/names-service
  - kubernetes/charts/verbs-service
